### ISSUE TITLE
scraper.rb:23:in `new': no implicit conversion from nil to integer (TypeError)

### ISSUE THREAD

**Issue by CloCkWeRX** [planningalerts-scrapers/casey#4]
```
scraper.rb:23:in `new': no implicit conversion from nil to integer (TypeError)
 	from scraper.rb:23:in `block in scrape_page'
 	from /app/vendor/bundle/ruby/2.0.0/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:187:in `block in each'
 	from /app/vendor/bundle/ruby/2.0.0/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:186:in `upto'
 	from /app/vendor/bundle/ruby/2.0.0/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:186:in `each'
 	from scraper.rb:8:in `scrape_page'
 	from scraper.rb:47:in `<main>'

```

**Comment by mlandauer** [comment]
Closing this as it looks not be relevant anymore
